// <auto-generated />

public partial class Shared_MasterPage
{
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl BodyTag;

    protected global::System.Web.UI.HtmlControls.HtmlForm form1;

    protected global::System.Web.UI.ScriptManager AppScriptManager;

    protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

    protected global::System.Web.UI.WebControls.ContentPlaceHolder SidebarContent;

    protected global::System.Web.UI.WebControls.ContentPlaceHolder SidebarFooter;

    protected global::System.Web.UI.WebControls.ContentPlaceHolder PageTitle;

    protected global::System.Web.UI.WebControls.ContentPlaceHolder PageStatus;

    protected global::System.Web.UI.WebControls.ContentPlaceHolder HeaderActions;

    protected global::System.Web.UI.HtmlControls.HtmlGenericControl UserInitials;

    protected global::System.Web.UI.WebControls.Label LblHeaderUser;

    protected global::System.Web.UI.WebControls.Label LblHeaderRole;

    protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
}
