// <auto-generated />

public partial class Bandeja
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;

    protected global::System.Web.UI.WebControls.Panel PnlSidebar;

    protected global::System.Web.UI.WebControls.Panel PnlMenuRegistrador;

    protected global::System.Web.UI.WebControls.LinkButton LnkNuevoTramite;

    protected global::System.Web.UI.WebControls.LinkButton LnkMisTramites;

    protected global::System.Web.UI.WebControls.Panel PnlMenuFirmador;

    protected global::System.Web.UI.WebControls.LinkButton LnkPendientesRev;

    protected global::System.Web.UI.WebControls.LinkButton LnkPendientesFirma;

    protected global::System.Web.UI.WebControls.LinkButton LnkCompletados;

    protected global::System.Web.UI.WebControls.Panel PnlMenuAdmin;

    protected global::System.Web.UI.WebControls.LinkButton LnkTodosTramites;

    protected global::System.Web.UI.WebControls.LinkButton LnkGestionarRoles;

    protected global::System.Web.UI.WebControls.LinkButton LnkCerrarSesion;

    protected global::System.Web.UI.WebControls.Label LblBienvenida;

    protected global::System.Web.UI.WebControls.Label LblError;

    protected global::System.Web.UI.WebControls.Label LblExito;

    protected global::System.Web.UI.WebControls.Label LblTituloBandeja;

    protected global::System.Web.UI.WebControls.TextBox TxtBuscar;

    protected global::System.Web.UI.WebControls.Button BtnBuscar;

    protected global::System.Web.UI.WebControls.Button BtnLimpiar;

    protected global::System.Web.UI.WebControls.GridView GvTramites;

    protected global::System.Web.UI.WebControls.Calendar CalBandeja;

    protected global::System.Web.UI.WebControls.LinkButton LnkLimpiarFiltroFecha;
}
