// <auto-generated />

public partial class Detalle
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;

    protected global::System.Web.UI.WebControls.Label LblCodigoDoc;

    protected global::System.Web.UI.WebControls.Label LblEstadoBadge;

    protected global::System.Web.UI.WebControls.Button BtnVolver;

    protected global::System.Web.UI.WebControls.Label LblError;

    protected global::System.Web.UI.WebControls.Label LblExito;

    protected global::System.Web.UI.WebControls.Label LblAsunto;

    protected global::System.Web.UI.WebControls.Label LblTipoDoc;

    protected global::System.Web.UI.WebControls.Label LblArea;

    protected global::System.Web.UI.WebControls.Label LblFechaDoc;

    protected global::System.Web.UI.WebControls.Label LblVersion;

    protected global::System.Web.UI.WebControls.Label LblRegistrador;

    protected global::System.Web.UI.WebControls.Label LblFechaLimite;

    protected global::System.Web.UI.WebControls.HiddenField HfRutaPDF;

    protected global::System.Web.UI.HtmlControls.HtmlIframe IframePDF;

    protected global::System.Web.UI.WebControls.GridView GvRevisores;

    protected global::System.Web.UI.WebControls.Panel PnlObservaciones;

    protected global::System.Web.UI.WebControls.Repeater RptObservaciones;

    protected global::System.Web.UI.WebControls.Panel PnlAccionesFirmador;

    protected global::System.Web.UI.WebControls.TextBox TxtObservacion;

    protected global::System.Web.UI.WebControls.Button BtnObservar;

    protected global::System.Web.UI.WebControls.Button BtnConforme;

    protected global::System.Web.UI.WebControls.Button BtnIrAFirmar;

    protected global::System.Web.UI.WebControls.Panel PnlAccionesRegistrador;

    protected global::System.Web.UI.WebControls.Button BtnRecordar;

    protected global::System.Web.UI.WebControls.Panel PnlCorreccion;

    protected global::System.Web.UI.WebControls.FileUpload FuPdfCorregido;

    protected global::System.Web.UI.WebControls.Button BtnCorregir;
}
