// <auto-generated />

public partial class FirmaDigital
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;

    protected global::System.Web.UI.WebControls.Panel PnlFirma;

    protected global::System.Web.UI.WebControls.LinkButton LnkVolver;

    protected global::System.Web.UI.WebControls.Label LblCodigoDoc;

    protected global::System.Web.UI.WebControls.Label LblAsunto;

    protected global::System.Web.UI.WebControls.Label LblError;

    protected global::System.Web.UI.WebControls.Button BtnDescargar;

    protected global::System.Web.UI.WebControls.FileUpload FuPdfFirmado;

    protected global::System.Web.UI.WebControls.TextBox TxtMotivo;

    protected global::System.Web.UI.WebControls.Button BtnSubirFirma;

    protected global::System.Web.UI.WebControls.Panel PnlExito;

    protected global::System.Web.UI.WebControls.Label LblMensajeExito;

    protected global::System.Web.UI.WebControls.Button BtnIrBandeja;
}
