// <auto-generated />

public partial class RegistrarTramite
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;

    protected global::System.Web.UI.WebControls.Label LblError;

    protected global::System.Web.UI.WebControls.Label LblExito;

    protected global::System.Web.UI.WebControls.FileUpload FuPdf;

    protected global::System.Web.UI.WebControls.TextBox TxtAreaResponsable;

    protected global::System.Web.UI.WebControls.RegularExpressionValidator RevArea;

    protected global::System.Web.UI.WebControls.DropDownList CbxTipoDocumento;

    protected global::System.Web.UI.WebControls.Label LblCodigoDocumento;

    protected global::System.Web.UI.WebControls.Label LblFechaDocumento;

    protected global::System.Web.UI.WebControls.TextBox TxtAsunto;

    protected global::System.Web.UI.WebControls.RegularExpressionValidator RevAsunto;

    protected global::System.Web.UI.WebControls.TextBox TxtFechaLimite;

    protected global::System.Web.UI.WebControls.GridView GvFirmantes;

    protected global::System.Web.UI.WebControls.Button BtnAgregarFirmante;

    protected global::System.Web.UI.WebControls.Button BtnRegistrar;
}
