// <auto-generated />

public partial class Login
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;

    protected global::System.Web.UI.WebControls.DropDownList CbxUsuario;

    protected global::System.Web.UI.WebControls.Button BtnIngresar;

    protected global::System.Web.UI.WebControls.Label LblError;
}
