// <auto-generated />

public partial class Dashboard
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;

    protected global::System.Web.UI.WebControls.Label LblAdminName;

    protected global::System.Web.UI.WebControls.LinkButton BtnNavStats;

    protected global::System.Web.UI.WebControls.LinkButton BtnNavTramites;

    protected global::System.Web.UI.WebControls.LinkButton BtnNavRoles;

    protected global::System.Web.UI.WebControls.LinkButton BtnNavOrden;

    protected global::System.Web.UI.WebControls.LinkButton BtnNavAuditoria;

    protected global::System.Web.UI.WebControls.LinkButton BtnLogout;

    protected global::System.Web.UI.WebControls.Label LblGlobalMsg;

    protected global::System.Web.UI.WebControls.Panel PnlStats;

    protected global::System.Web.UI.WebControls.Label LblTotal;

    protected global::System.Web.UI.WebControls.Label LblEnRev;

    protected global::System.Web.UI.WebControls.Label LblObs;

    protected global::System.Web.UI.WebControls.Label LblAprFirma;

    protected global::System.Web.UI.WebControls.Label LblEnFirma;

    protected global::System.Web.UI.WebControls.Label LblFPar;

    protected global::System.Web.UI.WebControls.Label LblCompletos;

    protected global::System.Web.UI.WebControls.Panel PnlTramites;

    protected global::System.Web.UI.WebControls.DropDownList DdlFiltroEstado;

    protected global::System.Web.UI.WebControls.GridView GvTodosTramites;

    protected global::System.Web.UI.WebControls.Panel PnlRoles;

    protected global::System.Web.UI.WebControls.GridView GvUsuarios;

    protected global::System.Web.UI.WebControls.Panel PnlOrden;

    protected global::System.Web.UI.WebControls.TextBox TxtBuscarDoc;

    protected global::System.Web.UI.WebControls.Button BtnBuscarDoc;

    protected global::System.Web.UI.WebControls.GridView GvDocsBusqueda;

    protected global::System.Web.UI.WebControls.Panel PnlEditarFirmantes;

    protected global::System.Web.UI.WebControls.Label LblDocEdicion;

    protected global::System.Web.UI.WebControls.GridView GvFirmantesEditar;

    protected global::System.Web.UI.WebControls.Button BtnGuardarOrden;

    protected global::System.Web.UI.WebControls.Panel PnlAuditoria;

    protected global::System.Web.UI.WebControls.TextBox TxtFechaDesde;

    protected global::System.Web.UI.WebControls.TextBox TxtFechaHasta;

    protected global::System.Web.UI.WebControls.TextBox TxtFiltroDocAuditoria;

    protected global::System.Web.UI.WebControls.Button BtnFiltrarAuditoria;

    protected global::System.Web.UI.WebControls.GridView GvAuditoria;
}
